source 'https://rubygems.org'

gem 'rails', '~> 4.0'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
end

##############################
gem 'bootstrap-sass', '3.3.5.1' # 부트스트랩 템플릿 젬
gem 'devise' # 회원가입을 도와주는 젬
gem 'simple_token_authentication', '~> 1.0'
gem 'will_paginate' # paginte 해주는 젬
gem 'will_paginate-bootstrap' # paginate 해주는 젬을 부트스트랩으로 꾸며주는 젬
gem 'simple_form'

gem 'carrierwave'
gem 'mini_magick'

gem 'sidekiq'
gem 'rpush'
gem 'rpush-redis'

gem 'sidekiq-cron', '~> 0.4.0'
gem 'redis'